#############   User Details   ##############

###############   POST user details  ##################
POST http://localhost:5000/user/details
Content-Type: application/json

{
    "name": "shubham",
    "address": "chittaranjan",
    "phn_no": 9002344,
    "email": "sd@gm.com",
    "key": "32",
    "dob": "2000, 11, 15"
}

#############    GET user details    ###################
GET http://localhost:5000/user/details

#############    PUT user details    ###################
PUT http://localhost:5000/user/details/601c33d59307a40bb4bf0487
Content-Type: application/json

{
    "name": "Iron Man"
}

#############   DELETE user details   ###################
DELETE http://localhost:5000/user/details

