#############   User Details   ##############

###############   POST user details  ##################
POST http://localhost:5000/user/details
Content-Type: application/json

{
    "name": "test",
    "address": "chittaranjan",
    "phn_no": 9002344,
    "email": "sd@gm.com",
    "key": "32",
    "dob": "2000, 11, 15",
    "password": "ThisIsSecrets",
    "layer": 5
}

#############    GET user details by id    ###################
POST http://localhost:5000/user/details/6026dd9e3ac3fb06ac02ddeb
Content-Type: application/json

{
  "password": "ThisIsSecrets"
}


#############    GET user details    ###################
GET http://localhost:5000/user/details



#############    PUT user details    ###################
PUT http://localhost:5000/user/details/601c5c8eba18d630e0e353da
Content-Type: application/json

{
    "name": "Iron Man"
}

#############   DELETE user details   ###################
DELETE http://localhost:5000/user/details






####################################     User Documents    #############################

##################   POST User Documents  ####################

POST http://localhost:5000/user/documents
Content-Type: application/json

{
    "adhaar_card_no": 44434276,
    "driver_license": "33sfdf4fdf",
    "panCard": [
      {
        "pan_card": "helloWorld"
      }
    ],
    "voter_auth": "helloMoto",
    "passport": "yoyoHoney"
}


#############    GET user documents    ###################
GET http://localhost:5000/user/documents

#############    PUT user documents    ###################
PUT http://localhost:5000/user/documents/601c46d940ddcb0c9c7287a5
Content-Type: application/json

{
    "passport": "bolbo na",
    "adhaar_card_no": 1234
}

#############   DELETE user documents   ###################
DELETE http://localhost:5000/user/documents








#############   User Career   ##############

###############   POST user career  ##################
POST http://localhost:5000/user/career
Content-Type: application/json

{
   "resume": "swapan.netlify.com",
    "career_instances": [
      {
        "company_name": "quordnet",
        "company_post": "null",
        "finance": [
          {
            "in_hand": "5000rs",
            "ctc": "45",
            "salary_slips": "3343"
          }
        ]
      }
    ],
    "non_service_persuits": [
      {
        "freelancing": "TCW",
        "bussiness": "group",
        "non_profits": "profitable"
      },
      {
        "freelancing": "QA",
        "bussiness": "group",
        "non_profits": "profitable"
      }
    ],
    "password": "secret",
    "layer": 4
}


#############   GET user career       ######################
GET http://localhost:5000/user/career

#############    GET user career by id   ###################
POST  http://localhost:5000/user/career/6026d9bb60e2640ba0ebd481
Content-Type: application/json

{
  "password": "secret"
}

#############    PUT user career    ###################
PUT http://localhost:5000/user/career/601c4a1bec15841c88446f35
Content-Type: application/json

{
  "career_instances": [
    {
    "finance": [
        {
          "in_hand": "4000rs"
        }
      ]
    }
  ]
}

#############    DELETE user career    ###################
DELETE  http://localhost:5000/user/career







#############   User Education   ##############

###############   POST user Education  ##################
POST http://localhost:5000/user/education
Content-Type: application/json

{
    "class_representative_boards": [
      {
        "marks": 90,
        "grade": "A",
        "admit_card": "abc.com",
        "registration_card": "xyz.com",
        "pass_certificate": "pqr.com",
        "grade_certificate": "hello.com"
      }
    ],
    "college": [
      {
        "degree": "BTECH",
        "course": "CSE",
        "discipline": "null",
        "semester_sheets": "null",
        "final_year_projects": ["memory-app", "eCommerce"],
        "degree_certificates": ["btech", "mca", "mtech"],
        "other_certificate": [
          {
            "academy": "web app ml",
            "sports": "cricket",
            "events": "quiz"
          }
        ]
      }
    ]
}

#############    GET user education    ###################
GET http://localhost:5000/user/education


#############    PUT user education    ###################
PATCH http://localhost:5000/user/education/601c501eda720d3568781517
Content-Type: application/json

{
    "college": {
      "course": "CST"
    }
}

#############   DELETE user education   ###################
DELETE http://localhost:5000/user/education







#############   User Finance   ##############

###############   POST user Finance  ##################
POST http://localhost:5000/user/finance
Content-Type: application/json

{
 "panCard": [
      {
        "panCard": "23325457"
      }
    ],
    "itr_forms": "abcd",
    "bank_transaction": "null",
    "assets": [
      {
        "commodities": "abcdef",
        "cryptocurrencies": "pqrs",
        "stocks": "hello",
        "mutual_funds": "null",
        "ipos": "null"
      }
    ]
}

#############    GET user education    ###################
GET http://localhost:5000/user/finance


#############    PUT user finance    ###################
PUT http://localhost:5000/user/finance/601c526d9a860747c8693571
Content-Type: application/json

{
    "itr_forms": "defgh",
    "bank_transaction": "defgh"
}

#############   DELETE user finance   ###################
DELETE http://localhost:5000/user/finance











#############   User Medical   ##############

###############   POST user Medical  ##################
POST http://localhost:5000/user/medical
Content-Type: application/json

{
  "vaccination_records": {
        "records": [
          {
            "vaccine_name": "covid vaccine",
            "vaccine_date": "2000, 9, 15",
            "administered_by": "2000, 9, 15",
            "administered_at": "2000, 9, 15"
          }
        ],
        "medical_illness_long_term": "not issued"
      }
}

#############    GET user education    ###################
GET http://localhost:5000/user/medical


#############    PUT user medical    ###################
PUT http://localhost:5000/user/medical/601c57ed7fe50646502be26d
Content-Type: application/json

{
  "vaccination_records": [{
    "records": [
      {
        "vaccine_name": "covid-19 virus recovery"
      }
    ]
  }]
}

#############   DELETE user medical   ###################
DELETE http://localhost:5000/user/medical
