export const CAREER_FETCH_REQUEST = "CAREER_FETCH_REQUEST";
export const CAREER_FETCH_SUCCESS = "CAREER_FETCH_SUCCESS";
export const CAREER_FETCH_FAILED = "CAREER_FETCH_FAILED";

export const CAREER_POST_REQUEST = "CAREER_POST_REQUEST";
export const CAREER_POST_SUCCESS = "CAREER_POST_SUCCESS";
export const CAREER_POST_FAILED = "CAREER_POST_FAILED";

export const CAREER_UPDATE_REQUEST = "CAREER_UPDATE_REQUEST";
export const CAREER_UPDATE_SUCCESS = "CAREER_UPDATE_SUCCESS";
export const CAREER_UPDATE_FAILED = "CAREER_UPDATE_FAILED";

export const CAREER_DELETE_REQUEST = "CAREER_DELETE_REQUEST";
export const CAREER_DELETE_SUCCESS = "CAREER_DELETE_SUCCESS";
export const CAREER_DELETE_FAILED = "CAREER_DELETE_FAILED";
