export const REQUEST_DETAILS = "REQUEST_DETAILS";
export const FETCH_DETAILS = "FETCH_DETAILS";
export const POST_DETAILS = "POST_DETAILS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const DELETE_DETAILS = "DELETE_DETAILS";
export const DETAILS_FAILED = "DETAILS_FAILED";
