export const DETAILS_FETCH_REQUEST = "DETAILS_FETCH_REQUEST";
export const DETAILS_FETCH_SUCCESS = "DETAILS_FETCH_SUCCESS";
export const DETAILS_FETCH_FAILED = "DETAILS_FETCH_FAILED";

export const DETAILS_POST_REQUEST = "DETAILS_POST_REQUEST";
export const DETAILS_POST_SUCCESS = "DETAILS_POST_SUCCESS";
export const DETAILS_POST_FAILED = "DETAILS_POST_FAILED";

export const DETAILS_UPDATE_REQUEST = "DETAILS_UPDATE_REQUEST";
export const DETAILS_UPDATE_SUCCESS = "DETAILS_UPDATE_SUCCESS";
export const DETAILS_UPDATE_FAILED = "DETAILS_UPDATE_FAILED";

export const DETAILS_DELETE_REQUEST = "DETAILS_DELETE_REQUEST";
export const DETAILS_DELETE_SUCCESS = "DETAILS_DELETE_SUCCESS";
export const DETAILS_DELETE_FAILED = "DETAILS_DELETE_FAILED";
