export const DOCUMENTS_FETCH_REQUEST = "DOCUMENTS_FETCH_REQUEST";
export const DOCUMENTS_FETCH_SUCCESS = "DOCUMENTS_FETCH_SUCCESS";
export const DOCUMENTS_FETCH_FAILED = "DOCUMENTS_FETCH_FAILED";

export const DOCUMENTS_POST_REQUEST = "DOCUMENTS_POST_REQUEST";
export const DOCUMENTS_POST_SUCCESS = "DOCUMENTS_POST_SUCCESS";
export const DOCUMENTS_POST_FAILED = "DOCUMENTS_POST_FAILED";

export const DOCUMENTS_UPDATE_REQUEST = "DOCUMENTS_UPDATE_REQUEST";
export const DOCUMENTS_UPDATE_SUCCESS = "DOCUMENTS_UPDATE_SUCCESS";
export const DOCUMENTS_UPDATE_FAILED = "DOCUMENTS_UPDATE_FAILED";

export const DOCUMENTS_DELETE_REQUEST = "DOCUMENTS_DELETE_REQUEST";
export const DOCUMENTS_DELETE_SUCCESS = "DOCUMENTS_DELETE_SUCCESS";
export const DOCUMENTS_DELETE_FAILED = "DOCUMENTS_DELETE_FAILED";
