export const EDUCATION_FETCH_REQUEST = "EDUCATION_FETCH_REQUEST";
export const EDUCATION_FETCH_SUCCESS = "EDUCATION_FETCH_SUCCESS";
export const EDUCATION_FETCH_FAILED = "EDUCATION_FETCH_FAILED";

export const EDUCATION_POST_REQUEST = "EDUCATION_POST_REQUEST";
export const EDUCATION_POST_SUCCESS = "EDUCATION_POST_SUCCESS";
export const EDUCATION_POST_FAILED = "EDUCATION_POST_FAILED";

export const EDUCATION_UPDATE_REQUEST = "EDUCATION_UPDATE_REQUEST";
export const EDUCATION_UPDATE_SUCCESS = "EDUCATION_UPDATE_SUCCESS";
export const EDUCATION_UPDATE_FAILED = "EDUCATION_UPDATE_FAILED";

export const EDUCATION_DELETE_REQUEST = "EDUCATION_DELETE_REQUEST";
export const EDUCATION_DELETE_SUCCESS = "EDUCATION_DELETE_SUCCESS";
export const EDUCATION_DELETE_FAILED = "EDUCATION_DELETE_FAILED";
