export const FINANCE_FETCH_REQUEST = "FINANCE_FETCH_REQUEST";
export const FINANCE_FETCH_SUCCESS = "FINANCE_FETCH_SUCCESS";
export const FINANCE_FETCH_FAILED = "FINANCE_FETCH_FAILED";

export const FINANCE_POST_REQUEST = "FINANCE_POST_REQUEST";
export const FINANCE_POST_SUCCESS = "FINANCE_POST_SUCCESS";
export const FINANCE_POST_FAILED = "FINANCE_POST_FAILED";

export const FINANCE_UPDATE_REQUEST = "FINANCE_UPDATE_REQUEST";
export const FINANCE_UPDATE_SUCCESS = "FINANCE_UPDATE_SUCCESS";
export const FINANCE_UPDATE_FAILED = "FINANCE_UPDATE_FAILED";

export const FINANCE_DELETE_REQUEST = "FINANCE_DELETE_REQUEST";
export const FINANCE_DELETE_SUCCESS = "FINANCE_DELETE_SUCCESS";
export const FINANCE_DELETE_FAILED = "FINANCE_DELETE_FAILED";
