export const MEDICAL_FETCH_REQUEST = "MEDICAL_FETCH_REQUEST";
export const MEDICAL_FETCH_SUCCESS = "MEDICAL_FETCH_SUCCESS";
export const MEDICAL_FETCH_FAILED = "MEDICAL_FETCH_FAILED";

export const MEDICAL_POST_REQUEST = "MEDICAL_POST_REQUEST";
export const MEDICAL_POST_SUCCESS = "MEDICAL_POST_SUCCESS";
export const MEDICAL_POST_FAILED = "MEDICAL_POST_FAILED";

export const MEDICAL_UPDATE_REQUEST = "MEDICAL_UPDATE_REQUEST";
export const MEDICAL_UPDATE_SUCCESS = "MEDICAL_UPDATE_SUCCESS";
export const MEDICAL_UPDATE_FAILED = "MEDICAL_UPDATE_FAILED";

export const MEDICAL_DELETE_REQUEST = "MEDICAL_DELETE_REQUEST";
export const MEDICAL_DELETE_SUCCESS = "MEDICAL_DELETE_SUCCESS";
export const MEDICAL_DELETE_FAILED = "MEDICAL_DELETE_FAILED";
